### PR TITLE
Create BeFake.swift

### PR DESCRIPTION
**Pull request by KeysDeveloper**

### CODE REVIEW

**Review by GraysonHuey — APPROVED** [review]

**Comment by GraysonHuey** [comment]
You said you don't know how pull requests work, but you did just fine lol

**Comment by KeysDeveloper** [comment]
I still have no clue what I did 💀

**Comment by GraysonHuey** [comment]
I'll record a video about how to use pull requests lol

**Comment by KeysDeveloper** [comment]
Ok lol

**Comment by GraysonHuey** [comment]
I know that  wanting to use pull requests might seem picky or whatever but I don't want anyone to accidentally break the code in the main branch and not be able to fix it

**Pull request merged**
